module.exports = {
    BROWSER_EXECUTABLE_PATH: '/home/lucas/Downloads/ungoogled-chromium-144.0.7559.132-1-x86_64_linux/chrome',
    COUNTS: 5,
    WORKERS: 1,
    FINGERPRINT_PLATFORM: 'macos',
    FINGERPRINT_PLATFORM_VERSION: '15.2.0',
    FINGERPRINT_BRAND: 'Chrome',
    FINGERPRINT_LANGUAGE: 'en-US',
    FINGERPRINT_ACCEPT_LANGUAGE: 'en-US,en',
    FINGERPRINT_WEBGL_VENDOR: 'Apple Inc.',
    FINGERPRINT_WEBGL_RENDERER: 'Apple M4',
    FINGERPRINT_DISABLE_SPOOFING: [],
    ADD_RECOVERY_EMAIL: false,
    MANUAL_VERIFICATION: true,
    HIDE_BROWSER_UNTIL_VERIFICATION: false,
    ENABLE_OAUTH2: true,
    OAUTH2_CLIENT_ID: '5c4acd45-93f4-471f-96e7-ac64ce35acf5',
    OAUTH2_REDIRECT_URL: 'http://localhost:5173',
    OAUTH2_SCOPES: [
      'offline_access',
      'https://graph.microsoft.com/Mail.ReadWrite',
      'https://graph.microsoft.com/Mail.Send',
      'https://graph.microsoft.com/User.Read',
    ],
    OAUTH_TOKENS_FILE: 'oauth_tokens.jsonl',
    OAUTH_TOKENS_TEXT_FILE: 'oauth_tokens.txt',
    PROXY_MODE: 'fixed',
    PROXY: 'http://127.0.0.1:7890',
    PROXY_POOL: [],
    PROXY_POOL_CONFIG_FILE: 'config/proxy_pool.yaml',
    PROXY_POOL_STATE_DIR: 'config/.runtime/proxy_pool',
    SING_BOX_PATH: '/home/lucas/.local/opt/sing-box/1.12.22/sing-box',
    NAMES_FILE: 'src/Utils/names.txt',
    WORDS_FILE: 'src/Utils/words5char.txt',
    ACCOUNTS_FILE: 'accounts.txt',
  };
